In [1]:
import sys
sys.path.append('../')

from wavy import *
import pandas as pd
%load_ext autoreload
%autoreload 2

In [2]:
data_pd = pd.read_pickle('processed.pkl')

In [3]:
datablock = from_dataframe(data_pd)
datablock

                  LNC                                                    MAS  \
                 Open       High        Low      Close     Volume       Open
Date
2005-12-21  38.127885  39.324626  38.120589  39.207870  2190100.0  18.991695
2005-12-22  39.185984  39.324630  38.879500  39.040039  1095500.0  19.085703
2005-12-23  39.061931  39.397604  38.959771  39.324631   588800.0  18.954090
2005-12-27  39.514374  39.514374  38.981676  39.237080   932700.0  18.929008
2005-12-28  39.455973  39.696782  39.244353  39.310028   427200.0  18.853798
...               ...        ...        ...        ...        ...        ...
2020-11-04  36.009998  36.900002  34.630001  35.029999  2770700.0  56.130001
2020-11-05  36.000000  36.799999  35.099998  35.900002  3318600.0  58.200001
2020-11-06  36.270000  36.689999  33.750000  34.070000  3075200.0  57.889999
2020-11-09  38.349998  44.360001  38.310001  42.630001  6787600.0  60.020000
2020-11-10  42.980000  42.990002  41.380001  42.439999  2861809.0  53.619999

                                                        ...        CSX  \
                 High        Low      Close     Volume  ...       Open
Date                                                    ...
2005-12-21  19.154659  18.903944  19.085712  1384200.0  ...   6.245725
2005-12-22  19.298810  18.910202  18.929007  1576900.0  ...   6.381336
2005-12-23  18.954090  18.684571  18.816196  2090500.0  ...   6.297691
2005-12-27  18.991687  18.803650  18.847525  1609000.0  ...   6.520750
2005-12-28  18.935281  18.747245  18.803656  2026300.0  ...   6.419358
...               ...        ...        ...        ...  ...        ...
2020-11-04  58.160000  55.580002  57.320000  1672900.0  ...  85.480003
2020-11-05  58.790001  57.580002  57.669998  1384500.0  ...  85.510002
2020-11-06  58.230000  57.200001  58.070000  2002800.0  ...  87.180000
2020-11-09  60.049999  53.720001  53.740002  3089400.0  ...  90.349998
2020-11-10  54.375000  52.990002  53.570000  3242839.0  ...  87.750000

                                                                CI  \
                 High        Low      Close     Volume        Open
Date
2005-12-21   6.399080   6.245725   6.362326  8358000.0   36.945102
2005-12-22   6.420626   6.361058   6.410487  5344800.0   37.409841
2005-12-23   6.520752   6.297691   6.468790  3630000.0   37.376876
2005-12-27   6.527087   6.369931   6.400348  4905000.0   37.195584
2005-12-28   6.459914   6.363592   6.419358  3578400.0   37.241735
...               ...        ...        ...        ...         ...
2020-11-04  87.550003  84.559998  84.830002  6449000.0  195.309998
2020-11-05  87.889999  85.000000  87.029999  6104000.0  208.500000
2020-11-06  87.690002  85.620003  86.180000  2890600.0  212.589996
2020-11-09  93.709999  88.019997  88.199997  5962900.0  215.160004
2020-11-10  91.879997  87.180000  91.400002  6167038.0  212.660004


                  High         Low       Close     Volume
Date
2005-12-21   37.462575   36.895658   37.370289  2805900.0
2005-12-22   37.630677   37.073647   37.327442  2296800.0
2005-12-23   37.432909   36.905546   37.261517  1686000.0
2005-12-27   37.455973   36.961570   37.116482  1917900.0
2005-12-28   37.449383   37.109892   37.251621  1248900.0
...                ...         ...         ...        ...
2020-11-04  212.580002  194.970001  210.619995  7051800.0
2020-11-05  217.750000  207.949997  214.160004  4441300.0
2020-11-06  212.820007  200.690002  201.470001  3648400.0
2020-11-09  217.210007  206.000000  211.199997  2686300.0
2020-11-10  221.500000  210.250000  220.199997  2787317.0

[3747 rows x 2085 columns]

In [4]:
datablock.swap_cols()
# list(datablock.channels)

                 Open                                                 \
                  LNC        MAS         AMT         IEX        QCOM
Date
2005-12-21  38.127885  18.991695   22.795099   21.938982   31.285869
2005-12-22  39.185984  19.085703   22.956885   22.220040   31.307121
2005-12-23  39.061931  18.954090   22.973916   22.145796   31.682183
2005-12-27  39.514374  18.929008   23.025008   22.241254   31.328345
2005-12-28  39.455973  18.853798   23.025007   21.870034   30.939137
...               ...        ...         ...         ...         ...
2020-11-04  36.009998  56.130001  234.699997  182.009995  129.320007
2020-11-05  36.000000  58.200001  240.279999  179.509995  145.820007
2020-11-06  36.270000  57.889999  239.910004  177.410004  146.009995
2020-11-09  38.349998  60.020000  249.160004  191.380005  149.410004
2020-11-10  42.980000  53.619999  238.929993  188.919998  140.148407

                                                                      ...  \
                  ANTM         GE        ADBE         BIO       EVRG  ...
Date                                                                  ...
2005-12-21   66.571808  21.133134   37.959999   63.349998  11.972113  ...
2005-12-22   66.082933  20.991315   37.450001   66.400002  11.912930  ...
2005-12-23   67.326575  21.224088   37.700001   65.750000  11.999024  ...
2005-12-27   67.240768  21.230061   37.450001   64.900002  11.955975  ...
2005-12-28   66.897702  20.925669   36.980000   64.599998  11.999024  ...
...                ...        ...         ...         ...        ...  ...
2020-11-04  312.799988   7.690000  477.929993  610.010010  56.840000  ...
2020-11-05  328.720001   7.950000  499.269989  638.460022  56.619999  ...
2020-11-06  317.929993   8.020000  494.950012  632.390015  55.299999  ...
2020-11-09  334.980011   9.350000  494.700012  648.390015  56.849998  ...
2020-11-10  323.049988   8.825000  466.720001  572.909973  57.970001  ...

               Volume                                                \
                  COO        REG        BIIB          CCL      ALGN
Date
2005-12-21  1691500.0   205200.0   2799100.0    2024300.0  253300.0
2005-12-22  2012500.0   146900.0   3294700.0    1392200.0  508400.0
2005-12-23  1118100.0    76800.0   1402000.0     973500.0  269200.0
2005-12-27  1129200.0   149600.0   3144200.0    1300200.0  327200.0
2005-12-28   635300.0   180300.0   2052300.0     913800.0  444500.0
...               ...        ...         ...          ...       ...
2020-11-04   204600.0  1099700.0  14591500.0   27613000.0  960200.0
2020-11-05   180200.0   898700.0   5070300.0   27600300.0  890800.0
2020-11-06   113800.0  2641800.0       600.0   19585600.0  664400.0
2020-11-09   410100.0  5278900.0   9239300.0  184797500.0  957200.0
2020-11-10   244921.0  2707102.0   3171899.0  118693921.0  668256.0


                    PFE        CPB         STX        CSX         CI
Date
2005-12-21   35302600.0   530100.0  35742800.0  8358000.0  2805900.0
2005-12-22   25183100.0   539800.0  13423400.0  5344800.0  2296800.0
2005-12-23   21614600.0   596200.0   4079000.0  3630000.0  1686000.0
2005-12-27   24956500.0   712700.0   2942700.0  4905000.0  1917900.0
2005-12-28   24069500.0   614700.0   3735900.0  3578400.0  1248900.0
...                 ...        ...         ...        ...        ...
2020-11-04   38776600.0  1149500.0   3435500.0  6449000.0  7051800.0
2020-11-05   32188800.0  1394900.0   3147500.0  6104000.0  4441300.0
2020-11-06   22647700.0  1104700.0   2880700.0  2890600.0  3648400.0
2020-11-09  217904600.0  3746700.0   4140900.0  5962900.0  2686300.0
2020-11-10   75032003.0  2192848.0   3659042.0  6167038.0  2787317.0

[3747 rows x 2085 columns]

In [5]:
datablock = datablock.filter(assets=['MSFT', 'AAPL'], channels=['Open', 'Close'])
datablock

                  MSFT                    AAPL
                  Open       Close        Open       Close
Date
2005-12-21   19.577126   19.475122    2.218566    2.246069
2005-12-22   19.460543   19.373114    2.258598    2.261960
2005-12-23   19.322122   19.409552    2.266543    2.241485
2005-12-27   19.438692   19.278402    2.261349    2.268378
2005-12-28   19.314840   19.227409    2.275712    2.248209
...                ...         ...         ...         ...
2020-11-04  214.020004  216.389999  113.943419  114.752022
2020-11-05  222.039993  223.289993  117.746855  118.824997
2020-11-06  222.259995  223.720001  118.320000  118.690002
2020-11-09  224.440002  218.389999  120.500000  116.320000
2020-11-10  214.500000  211.009995  115.550003  115.970001

[3747 rows x 4 columns]

In [8]:
datablock.apply(np.max, on='rows')

         MSFT                    AAPL
         Open       Close        Open       Close
0  229.270004  231.649994  137.353033  133.948898

In [ ]:
datablock.assets

In [ ]:
datablock.columns.levels[0]

In [ ]:
datablock = datablock.rename_assets({'AAPL': 'Apple'})
datablock = datablock.rename_channels({'Open': 'Op'})

datablock

In [ ]:
datablock.columns

In [ ]:
datablock.columns.levels[1]

In [ ]:
datablock = datablock.apply(np.max, axis=1)

In [ ]:
datablock

In [ ]:
datablock.columns.levels[1]

In [ ]:
datablock.sort_assets()

In [ ]:
datablock.columns.levels[0]

In [ ]:
datablock = datablock.swap_cols()

In [ ]:
datablock.columns.levels[0]

In [ ]:
datablock.columns.levels[1]

In [ ]:
datablock.assets

In [ ]:
datablock.channels