In [1]:
import sys
sys.path.append('../')

%load_ext autoreload
%autoreload 2

In [2]:
# Import the necessary modules
import wavy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

/Users/ibiscp/GitHub/logspace/wavy/.venv/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv('../data/train.csv')

In [4]:
# df['congestion'] = df['congestion']/100

In [5]:
df['key'] = df.apply(lambda x: str(x['x']) + '_' + str(x['y']) + '_' + x['direction'], axis=1)

In [6]:
df.drop(['row_id', 'x', 'y', 'direction'], axis=1, inplace=True)

In [7]:
df

                       time  congestion     key
0       1991-04-01 00:00:00          70  0_0_EB
1       1991-04-01 00:00:00          49  0_0_NB
2       1991-04-01 00:00:00          24  0_0_SB
3       1991-04-01 00:00:00          18  0_1_EB
4       1991-04-01 00:00:00          60  0_1_NB
...                     ...         ...     ...
848830  1991-09-30 11:40:00          54  2_3_NB
848831  1991-09-30 11:40:00          28  2_3_NE
848832  1991-09-30 11:40:00          68  2_3_SB
848833  1991-09-30 11:40:00          17  2_3_SW
848834  1991-09-30 11:40:00          24  2_3_WB

[848835 rows x 3 columns]

In [8]:
df = df.pivot(index='time', columns='key', values='congestion')

In [9]:
df

key,0_0_EB,0_0_NB,0_0_SB,0_1_EB,0_1_NB,0_1_SB,0_1_WB,0_2_EB,0_2_NB,0_2_SB,...,2_2_SB,2_2_SE,2_2_SW,2_2_WB,2_3_EB,2_3_NB,2_3_NE,2_3_SB,2_3_SW,2_3_WB
time,,,,,,,,,,,,,,,,,,,,,
1991-04-01 00:00:00,70,49,24,18,60,58,26,31,49,46,...,36,51,47,51,39,64,30,70,29,26
1991-04-01 00:20:00,70,49,24,26,64,55,57,41,40,46,...,10,51,50,58,33,67,30,80,29,57
1991-04-01 00:40:00,70,49,24,31,51,57,91,42,41,35,...,32,51,49,63,33,64,30,79,29,48
1991-04-01 01:00:00,70,49,24,36,51,46,49,39,44,58,...,60,51,49,52,33,33,30,77,29,44
1991-04-01 01:20:00,70,49,24,29,53,83,62,36,46,46,...,43,51,49,50,33,50,30,79,29,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991-09-30 10:20:00,43,29,60,23,63,61,42,47,51,56,...,66,20,50,70,90,53,29,68,22,49
1991-09-30 10:40:00,47,28,35,24,62,63,32,44,57,65,...,60,21,49,68,45,52,25,70,20,47
1991-09-30 11:00:00,40,31,53,22,65,58,38,44,60,62,...,58,27,53,68,44,58,29,69,19,37
1991-09-30 11:20:00,52,36,59,35,67,54,26,44,59,57,...,52,20,53,67,57,59,22,69,22,53
1991-09-30 11:40:00,70,40,51,24,65,52,42,43,62,77,...,64,40,51,71,48,54,28,68,17,24

In [10]:
df.index = pd.to_datetime(df.index)

In [11]:
df

key,0_0_EB,0_0_NB,0_0_SB,0_1_EB,0_1_NB,0_1_SB,0_1_WB,0_2_EB,0_2_NB,0_2_SB,...,2_2_SB,2_2_SE,2_2_SW,2_2_WB,2_3_EB,2_3_NB,2_3_NE,2_3_SB,2_3_SW,2_3_WB
time,,,,,,,,,,,,,,,,,,,,,
1991-04-01 00:00:00,70,49,24,18,60,58,26,31,49,46,...,36,51,47,51,39,64,30,70,29,26
1991-04-01 00:20:00,70,49,24,26,64,55,57,41,40,46,...,10,51,50,58,33,67,30,80,29,57
1991-04-01 00:40:00,70,49,24,31,51,57,91,42,41,35,...,32,51,49,63,33,64,30,79,29,48
1991-04-01 01:00:00,70,49,24,36,51,46,49,39,44,58,...,60,51,49,52,33,33,30,77,29,44
1991-04-01 01:20:00,70,49,24,29,53,83,62,36,46,46,...,43,51,49,50,33,50,30,79,29,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991-09-30 10:20:00,43,29,60,23,63,61,42,47,51,56,...,66,20,50,70,90,53,29,68,22,49
1991-09-30 10:40:00,47,28,35,24,62,63,32,44,57,65,...,60,21,49,68,45,52,25,70,20,47
1991-09-30 11:00:00,40,31,53,22,65,58,38,44,60,62,...,58,27,53,68,44,58,29,69,19,37
1991-09-30 11:20:00,52,36,59,35,67,54,26,44,59,57,...,52,20,53,67,57,59,22,69,22,53
1991-09-30 11:40:00,70,40,51,24,65,52,42,43,62,77,...,64,40,51,71,48,54,28,68,17,24

In [12]:
df = df.resample('20min')

In [13]:
df

In [14]:
interpolated = df.interpolate(method='linear')

In [15]:
interpolated

key,0_0_EB,0_0_NB,0_0_SB,0_1_EB,0_1_NB,0_1_SB,0_1_WB,0_2_EB,0_2_NB,0_2_SB,...,2_2_SB,2_2_SE,2_2_SW,2_2_WB,2_3_EB,2_3_NB,2_3_NE,2_3_SB,2_3_SW,2_3_WB
time,,,,,,,,,,,,,,,,,,,,,
1991-04-01 00:00:00,70.0,49.0,24.0,18.0,60.0,58.0,26.0,31.0,49.0,46.0,...,36.0,51.0,47.0,51.0,39.0,64.0,30.0,70.0,29.0,26.0
1991-04-01 00:20:00,70.0,49.0,24.0,26.0,64.0,55.0,57.0,41.0,40.0,46.0,...,10.0,51.0,50.0,58.0,33.0,67.0,30.0,80.0,29.0,57.0
1991-04-01 00:40:00,70.0,49.0,24.0,31.0,51.0,57.0,91.0,42.0,41.0,35.0,...,32.0,51.0,49.0,63.0,33.0,64.0,30.0,79.0,29.0,48.0
1991-04-01 01:00:00,70.0,49.0,24.0,36.0,51.0,46.0,49.0,39.0,44.0,58.0,...,60.0,51.0,49.0,52.0,33.0,33.0,30.0,77.0,29.0,44.0
1991-04-01 01:20:00,70.0,49.0,24.0,29.0,53.0,83.0,62.0,36.0,46.0,46.0,...,43.0,51.0,49.0,50.0,33.0,50.0,30.0,79.0,29.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991-09-30 10:20:00,43.0,29.0,60.0,23.0,63.0,61.0,42.0,47.0,51.0,56.0,...,66.0,20.0,50.0,70.0,90.0,53.0,29.0,68.0,22.0,49.0
1991-09-30 10:40:00,47.0,28.0,35.0,24.0,62.0,63.0,32.0,44.0,57.0,65.0,...,60.0,21.0,49.0,68.0,45.0,52.0,25.0,70.0,20.0,47.0
1991-09-30 11:00:00,40.0,31.0,53.0,22.0,65.0,58.0,38.0,44.0,60.0,62.0,...,58.0,27.0,53.0,68.0,44.0,58.0,29.0,69.0,19.0,37.0
1991-09-30 11:20:00,52.0,36.0,59.0,35.0,67.0,54.0,26.0,44.0,59.0,57.0,...,52.0,20.0,53.0,67.0,57.0,59.0,22.0,69.0,22.0,53.0
1991-09-30 11:40:00,70.0,40.0,51.0,24.0,65.0,52.0,42.0,43.0,62.0,77.0,...,64.0,40.0,51.0,71.0,48.0,54.0,28.0,68.0,17.0,24.0

In [16]:
x, y = wavy.create_panels(interpolated, lookback=24*3, gap=0, horizon=12*3)

In [17]:
x.indices

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [ ]:
y[0].columns.name

In [18]:
y = y.max()

In [ ]:
y[0].columns.name

In [ ]:
x.indices

In [19]:
y.indices

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [ ]:
# scaling function for input data
def minmax_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    return numerator / (denominator + 1e-7)

In [ ]:
x_train = x.train

In [ ]:
x_train_scaled = minmax_scaler(x_train.values)

In [ ]:
x_train = x_train.update(x_train_scaled)

In [ ]:
x = x[2:]

In [ ]:
len(x)

In [ ]:
y = y.match(x)

In [ ]:
len(y)

In [ ]:
print(f"Training set size: {x.train_size}")
print(f"Validation set size: {x.val_size}")
print(f"Test set size: {x.test_size}")

In [ ]:
x.set_training_split(val_split=0.1, test_size=0.0)

In [ ]:
print(f"Training set size: {x.train_size}")
print(f"Validation set size: {x.val_size}")
print(f"Test set size: {x.test_size}")

In [ ]:
x = x.update(x.values)

In [ ]:
print(f"Training set size: {x.train_size}")
print(f"Validation set size: {x.val_size}")
print(f"Test set size: {x.test_size}")

In [ ]:
type(y)

In [ ]:
y = y.match(x)

In [ ]:
y=y.match(x)

In [ ]:
print(f"Training set size: {y.train_size}")
print(f"Validation set size: {y.val_size}")
print(f"Test set size: {y.test_size}")

In [ ]:
x[:5]

In [ ]:
x = x[:10]

In [ ]:
y = y.match(x)

In [ ]:
# TODO: Wrong to use scaler
scaler = StandardScaler()
scaler.fit(x.train.values.reshape(-1, x.train.values.shape[-1]))
x_new = scaler.transform(x.values.reshape(-1, x.shape[-1])).reshape(x.shape)
x = x.update(x_new)

In [ ]:
x = x/100

In [ ]:
densemodel = wavy.DenseModel(x, y, model_type='regression')
densemodel.fit(epochs=50)

In [ ]:
densemodel.score()

In [ ]:
convmodel = wavy.ConvModel(x, y, model_type='regression')
convmodel.fit(epochs=50)

In [ ]:
convmodel.score()

In [ ]:
baseline = wavy.BaselineShift(x, y, model_type='regression')
baseline.fit()

In [ ]:
baseline.score()